version: 2

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign

linters-settings:
  govet:
    # Enable all checks
    checks:
      - all

issues:
  exclude-rules:
    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - errcheck

run:
  timeout: 5m
