linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck

linters-settings:
  gofmt:
    simplify: true

issues:
  exclude-rules:
    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - errcheck
        - staticcheck
